/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MapRouteImport } from './routes/map'
import { Route as AcademicGraduationRouteImport } from './routes/academic.graduation'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminFileFailuresRouteImport } from './routes/admin.file-failures'
import { Route as FormTypeRouteImport } from './routes/form.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicGraduationRoute = AcademicGraduationRouteImport.update({
  id: '/academic/graduation',
  path: '/academic/graduation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFileFailuresRoute = AdminFileFailuresRouteImport.update({
  id: '/file-failures',
  path: '/file-failures',
  getParentRoute: () => AdminRoute,
} as any)
const FormTypeRoute = FormTypeRouteImport.update({
  id: '/form/$type',
  path: '/form/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/map': typeof MapRoute
  '/academic/graduation': typeof AcademicGraduationRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/file-failures': typeof AdminFileFailuresRoute
  '/form/$type': typeof FormTypeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/map': typeof MapRoute
  '/academic/graduation': typeof AcademicGraduationRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/file-failures': typeof AdminFileFailuresRoute
  '/form/$type': typeof FormTypeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/map': typeof MapRoute
  '/academic/graduation': typeof AcademicGraduationRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/file-failures': typeof AdminFileFailuresRoute
  '/form/$type': typeof FormTypeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/map'
    | '/academic/graduation'
    | '/admin/emails'
    | '/admin/file-failures'
    | '/form/$type'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/map'
    | '/academic/graduation'
    | '/admin/emails'
    | '/admin/file-failures'
    | '/form/$type'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/map'
    | '/academic/graduation'
    | '/admin/emails'
    | '/admin/file-failures'
    | '/form/$type'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  MapRoute: typeof MapRoute
  AcademicGraduationRoute: typeof AcademicGraduationRoute
  FormTypeRoute: typeof FormTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/graduation': {
      id: '/academic/graduation'
      path: '/academic/graduation'
      fullPath: '/academic/graduation'
      preLoaderRoute: typeof AcademicGraduationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/file-failures': {
      id: '/admin/file-failures'
      path: '/file-failures'
      fullPath: '/admin/file-failures'
      preLoaderRoute: typeof AdminFileFailuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/form/$type': {
      id: '/form/$type'
      path: '/form/$type'
      fullPath: '/form/$type'
      preLoaderRoute: typeof FormTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminFileFailuresRoute: typeof AdminFileFailuresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmailsRoute: AdminEmailsRoute,
  AdminFileFailuresRoute: AdminFileFailuresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  MapRoute: MapRoute,
  AcademicGraduationRoute: AcademicGraduationRoute,
  FormTypeRoute: FormTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
