import { infiniteQueryOptions, queryOptions } from '@tanstack/react-query';
import type {
  DetailPage,
  GraduationManifest,
  GraduationOverview,
} from '~/pages/academic/graduation/types';
import { queryKeys } from '~/queries/keys';

const BASE = '/data/graduation';

const fetchJson = async <T>(url: string, label: string): Promise<T> => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${label} ${res.status}`);
  return (await res.json()) as T;
};

/**
 * The chunks are regenerated by hand (pnpm graduation:build), so once a tab has
 * them there is no reason to refetch — the whole page is a few cold requests.
 */
const FROZEN = { staleTime: Infinity, gcTime: Infinity } as const;

export const graduationManifestQueryOptions = () =>
  queryOptions({
    queryKey: queryKeys.graduationManifest(),
    queryFn: () =>
      fetchJson<GraduationManifest>(
        `${BASE}/manifest.json`,
        'graduation manifest',
      ),
    ...FROZEN,
  });

export const graduationOverviewQueryOptions = () =>
  queryOptions({
    queryKey: queryKeys.graduationOverview(),
    queryFn: () =>
      fetchJson<GraduationOverview>(
        `${BASE}/overview.json`,
        'graduation overview',
      ),
    ...FROZEN,
  });

const ALL = 'all';

/**
 * The 单位 ranking for one (院系 × 届 × 学历) view.
 *
 * The build ships each view pre-summed and pre-ranked, splitting only the 18
 * views that outgrow its size budget — so this usually settles in one request
 * and `hasMore` is simply absent. 去向 is deliberately not part of the shard
 * key: masking already pairs (类别, 单位), so filtering a category out of a
 * mixed page yields the same numbers a dedicated shard would, and putting it
 * in the path would have quadrupled the file count for nothing.
 */
export const graduationDetailQueryOptions = (
  collegeId: string | null,
  grade: number | null,
  educationIndex: number | null,
) => {
  const scope = collegeId ?? ALL;
  const facet = `${grade ?? ALL}-${educationIndex ?? ALL}`;
  return infiniteQueryOptions({
    queryKey: queryKeys.graduationDetail(scope, facet),
    queryFn: ({ pageParam }) =>
      fetchJson<DetailPage>(
        `${BASE}/detail/${scope}/${facet}/${pageParam}.json`,
        `graduation detail ${scope}/${facet}/${pageParam}`,
      ),
    initialPageParam: 0,
    // Each page declares whether another exists, so no row arithmetic here.
    getNextPageParam: (last, all) => (last.hasMore ? all.length : undefined),
    ...FROZEN,
  });
};
